import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

class EmailService:
    def __init__(self):
        self.app_password = os.getenv('GMAIL_APP_PASSWORD')
        self.sender_email = os.getenv('SENDER_EMAIL')
        self.smtp_server = "smtp.gmail.com"
        self.smtp_port = 587

    def send_schedule_approval_email(self, program_name: str, recipients: list[str]):
        if not self.app_password or not self.sender_email:
            print("WARNING: Gmail App Password / Sender Email not found in .env. Skipping email dispatch.")
            return

        subject = f"Schedule Finalized for {program_name}!"
        
        # We send 'TO' ourselves, and 'BCC' everyone else to hide member emails
        bcc_list = list(set([r for r in recipients if r != self.sender_email]))

        html_content = f"""
        <html>
        <head></head>
        <body>
            <div style="font-family: 'Inter', sans-serif; color: #1a1a1a; max-width: 600px; margin: 0 auto; padding: 20px; border-radius: 12px; border: 1px solid #e2e8f0; background-color: #ffffff;">
                <div style="text-align: center; margin-bottom: 24px;">
                    <h1 style="color: #4f46e5; margin: 0; font-size: 28px;">Event-Scheduler AI</h1>
                    <p style="color: #64748b; font-size: 14px; margin-top: 4px;">Schedule Approved</p>
                </div>
                
                <h2 style="font-size: 20px; font-weight: 600; margin-bottom: 16px;">Hello Team,</h2>
                <p style="font-size: 16px; line-height: 1.6; color: #334155;">
                    Great news! The official schedule for <strong>{program_name}</strong> has just been generated by our AI and formally approved by the Organising Committee.
                </p>
                <p style="font-size: 16px; line-height: 1.6; color: #334155;">
                    You can now log into the dashboard to check your venue assignments, timings, and volunteer duties.
                </p>
                
                <div style="margin-top: 32px; padding-top: 24px; border-top: 1px solid #f1f5f9; text-align: center;">
                    <a href="#" style="background-color: #4f46e5; color: white; padding: 12px 24px; text-decoration: none; border-radius: 8px; font-weight: 600; display: inline-block;">View Schedule</a>
                </div>
            </div>
        </body>
        </html>
        """

        msg = MIMEMultipart('alternative')
        msg['Subject'] = subject
        msg['From'] = f"Event Scheduler <{self.sender_email}>"
        msg['To'] = self.sender_email
        
        # Smtplib handles BCC slightly differently than APIs: 
        # You don't put it in the header (which exposes it), you just pass the list to the `sendmail` command.
        
        part = MIMEText(html_content, 'html')
        msg.attach(part)

        try:
            # Login and send
            server = smtplib.SMTP(self.smtp_server, self.smtp_port)
            server.starttls()
            server.login(self.sender_email, self.app_password)
            
            all_envelope_recipients = [self.sender_email] + bcc_list
            
            server.sendmail(
                self.sender_email, 
                all_envelope_recipients, 
                msg.as_string()
            )
            server.quit()
            print(f"Gmail SMTP Dispatch Success to {len(all_envelope_recipients)} people!")
        except Exception as e:
            print(f"Gmail SMTP Error: {str(e)}")

email_dispatcher = EmailService()
